# {{crate}}

{{readme}}

## A note about this file (`README.md` in the `ipp-sys` crate)

This file is automatically generated from the `ipp-sys` docstring by running the
following command:

    cargo readme > README.md
