[![crates.io](https://meritbadge.herokuapp.com/ipp-sys)](https://crates.io/crates/ipp-sys)

# ipp-sys - Bindings to Intel Integrated Performance Primitives (Intel IPP).

This directory contains several crates:

 - `ipp-sys`: toplevel convenience crate that depends on `ipp-headers-sys` and `link-*` crates
 - `ipp-headers-sys`: provide FFI headers from `ipp.h` (made with `bindgen`)
 - `ipp-sys-build-help`: helper for build.rs in the `link-*` crates
 - `link-ippcore`: link ippcore library
 - `link-ippcv`: link ippcv library
 - `link-ippi`: link ippi library
 - `link-ipps`: link ipps library
 - `link-ippvm`: link ippvm library

Typically, you can just depend on `ipp-sys`. The `link-*` crates do not provide
any rust code, but only serve to link the relevant IPP library. There are
multiple `link-*` crates because [the Cargo manifest `links` field supports only
linking only a single library per
crate](https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key).

{{readme}}

## License

The `ipp-sys` Rust crates are licensed under either of

* Apache License, Version 2.0,
  (./LICENSE-APACHE or http://www.apache.org/licenses/LICENSE-2.0)
* MIT license (./LICENSE-MIT or http://opensource.org/licenses/MIT)
  at your option.

Please consult documentation for the [Intel
IPP](https://software.intel.com/en-us/intel-ipp) library for its license.

## Contribution

Unless you explicitly state otherwise, any contribution intentionally
submitted for inclusion in the work by you, as defined in the Apache-2.0
license, shall be dual licensed as above, without any additional terms or
conditions.

The canonical source code repository and issue tracker are on the [ipp-sys
github page](https://github.com/astraw/ipp-sys).

## Code of conduct

Anyone who interacts with ipp-sys in any space including but not limited to
this GitHub repository is expected to follow our [code of
conduct](https://github.com/astraw/ipp-sys/blob/master/code_of_conduct.md).

## A note about this file (the top-level `README.md`)

This file is automatically generated from the `ipp-sys` docstring by running the
following command:

    cargo readme --project-root ipp-sys --template ../README.tpl  > README.md